apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: account
  name: account
  namespace: default
spec:
  replicas: 1
  minReadySeconds: 45
  selector:
    matchLabels:
      app: account
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: account
    spec:
      containers:
      - image: anithait/account-service:0.0.1-RELEASE
        imagePullPolicy: IfNotPresent
        name: account
        env:
        - name: TRANSACTION_SERIVCE_HOST
          value: transaction
        resources:
          limits:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
      restartPolicy: Always    
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: account
  name: account
  namespace: default
spec:
  ports:
  - #nodePort: 31127
    port: 8003
    protocol: TCP
    targetPort: 8003
  selector:
    app: account
  sessionAffinity: None
  type: LoadBalancer


